"""Ports implemented by ComfyUI transport adapters."""

from __future__ import annotations

import builtins
from collections.abc import Callable, Generator
from typing import Any, Protocol

from comfyui_mcp_skills.domain.models import Asset, Job, Workflow


class WorkflowRepository(Protocol):
    def list(self) -> list[Workflow]: ...
    def get(self, server_id: str, workflow_id: str) -> Workflow | None: ...
    def list_revisions(self, workflow_id: str) -> builtins.list[dict[str, Any]]: ...
    def describe(self, workflow_id: str, server_id: str) -> dict[str, Any]: ...
    def get_revision(self, revision_id: str) -> dict[str, Any]: ...
    def get_published_revision(self, workflow_id: str) -> dict[str, Any]: ...
    def create_revision(
        self,
        *,
        workflow_id: str,
        server_id: str,
        graph: dict[str, Any],
        parameter_schema: dict[str, Any],
        dependency_contract: dict[str, Any],
        content_digest: str,
    ) -> dict[str, Any]: ...


class RunRepository(Protocol):
    def claim(
        self,
        server_id: str,
        workflow_id: str,
        idempotency_key: str,
        arguments: dict[str, Any],
        owner_id: str = "",
        client_id: str = "",
    ) -> str | None: ...
    def get_claim(self, server_id: str, key: str, owner_id: str = "") -> dict[str, Any] | None: ...
    def release_claim(
        self,
        server_id: str,
        key: str,
        request_digest: str,
        lease_token: str,
        owner_id: str = "",
    ) -> None: ...
    def mark_submission_unknown(
        self,
        server_id: str,
        key: str,
        lease_token: str,
        owner_id: str = "",
    ) -> None: ...
    def request_digest(self, workflow_id: str, arguments: dict[str, Any]) -> str: ...
    def save(self, job: Job, *, lease_token: str = "") -> None: ...
    def get(self, server_id: str, prompt_id: str) -> Job | None: ...
    def get_by_idempotency(self, server_id: str, key: str, owner_id: str = "") -> Job | None: ...
    def list_jobs(
        self,
        owner_id: str,
        *,
        limit: int,
        status: str = "",
        workflow_id: str = "",
        server_id: str = "",
        created_after: str = "",
        after_created_at: str = "",
        after_job_id: str = "",
    ) -> builtins.list[dict[str, str]]: ...


class AssetRepository(Protocol):
    def save(self, asset: Asset) -> None: ...
    def get(self, asset_id: str) -> Asset | None: ...


class ComfyUIGateway(Protocol):
    def queue_prompt(self, workflow: dict[str, Any], **kwargs: Any) -> dict[str, Any]: ...
    def get_system_stats(self) -> dict[str, Any]: ...
    def get_object_info(self) -> dict[str, Any]: ...
    def get_object_info_node(self, node_class: str) -> dict[str, Any] | None: ...
    def get_model_folders(self) -> list[str]: ...
    def get_models(self, folder: str) -> list[str]: ...
    def get_history_list(self, max_items: int = 20, offset: int = 0) -> dict[str, Any]: ...
    def get_history(
        self, prompt_id: str, *, timeout_seconds: float | None = None
    ) -> dict[str, Any] | None: ...
    def get_queue(self, *, timeout_seconds: float | None = None) -> dict[str, Any]: ...
    def interrupt(self, prompt_id: str = "") -> dict[str, Any]: ...
    def queue_delete(self, prompt_ids: list[str]) -> dict[str, Any]: ...
    def get_logs(self) -> dict[str, Any]: ...
    def get_workflow_templates(self) -> dict[str, Any]: ...
    def get_subgraphs(self) -> dict[str, Any]: ...
    def get_subgraph(self, subgraph_id: str) -> dict[str, Any]: ...
    def get_capabilities(self) -> dict[str, Any]: ...
    def free_memory(self, *, unload_models: bool, free_memory: bool) -> dict[str, Any]: ...
    def upload_file(self, path: str, *, purpose: str, original_ref: str) -> dict[str, Any]: ...
    def download_output(
        self,
        filename: str,
        subfolder: str = "",
        output_type: str = "output",
        *,
        max_bytes: int,
    ) -> bytes: ...
    def ws_events(
        self,
        client_id: str,
        prompt_id: str,
        timeout_seconds: float | None = None,
        cancel_check: Callable[[], None] | None = None,
    ) -> Generator[dict[str, Any], None, None]: ...
